# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='sentence_1',
            new_name='sentence',
        ),
    ]
